import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// DocumentScannerOCR — generated by AppFactoryKit appgen from niche "document-scanner".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum DocumentScannerOCRFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "DocumentScannerOCR",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "doc.viewfinder",
                          title: "DocumentScannerOCR",
                          message: "Scan docs to PDF, OCR, sign, export."),
                    .init(systemImage: "doc.text.magnifyingglass",
                          title: "Go Pro",
                          message: "Unlimited scans, OCR, signature, no watermark.")
                ],
                presentsPaywallOnFinish: true,
                accent: .blue
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock DocumentScannerOCR Pro",
                subheadline: "Unlimited scans, OCR, signature, no watermark.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited scans"),
                    .init(systemImage: "bolt.fill", title: "OCR"),
                    .init(systemImage: "nosign", title: "Signature"),
                    .init(systemImage: "square.and.arrow.up", title: "No watermark")
                ],
                productIDs: ["document-scanner_yearly", "document-scanner_weekly"],
                highlightedProductID: "document-scanner_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .blue, heroSystemImage: "doc.viewfinder")
            )
        )
        return AppFactory(config)
    }
}

@main
struct DocumentScannerOCRApp: App {
    @StateObject private var factory = DocumentScannerOCRFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.blue)
        }
    }
}
